name: Deploy to EC2

on:
  push:
    branches: [ main, production ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install backend dependencies
        run: |
          cd backend
          npm ci
      
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci
      
      - name: Build backend
        run: |
          cd backend
          npm run build
      
      - name: Build frontend
        run: |
          cd frontend
          npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ${{ secrets.EC2_USER }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          # Copy environment file
          scp -i private_key.pem -o StrictHostKeyChecking=no env.production.template ${USER}@${HOST}:/home/ubuntu/app/backend/.env
          
          # Deploy application
          ssh -i private_key.pem -o StrictHostKeyChecking=no ${USER}@${HOST} '
            cd /home/ubuntu/app &&
            if [ -d ".git" ]; then
              git pull origin main
            else
              echo "Not a git repository, skipping git pull"
            fi &&
            npm install &&
            npm run build &&
            pm2 reload ecosystem.config.js --env production
          '
          
          rm -f private_key.pem
