name: Deploy to EC2

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install backend dependencies
        run: |
          cd backend
          npm ci
      
      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci
      
      - name: Build backend
        run: |
          cd backend
          npm run build
      
      - name: Build frontend
        run: |
          cd frontend
          npm run build

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /var/www/immigration-portal
            git fetch origin
            git reset --hard origin/main
            git clean -fd
            
            # Create .env file for PM2 to use
            cat > backend/.env << EOF
            NODE_ENV=production
            PORT=5000
            MONGODB_URI=${{ secrets.MONGODB_URI }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }}
            FRONTEND_URL=${{ secrets.FRONTEND_URL }}
            SUPER_ADMIN_FRONTEND_URL=${{ secrets.FRONTEND_URL }}
            TENANT_FRONTEND_URL_TEMPLATE=https://{domain}/immigration-portal
            ALLOWED_SUPER_ADMIN_DOMAINS=${{ secrets.SUPER_ADMIN_DOMAIN }},www.${{ secrets.SUPER_ADMIN_DOMAIN }}
            ALLOW_START_WITHOUT_DB=false
            REDIS_ENABLED=false
            NEW_RELIC_LICENSE_KEY=${{ secrets.NEW_RELIC_LICENSE_KEY }}
            NEW_RELIC_APP_NAME=${{ secrets.NEW_RELIC_APP_NAME }}
            NEW_RELIC_AI_MONITORING_ENABLED=true
            SUPER_ADMIN_DOMAIN=${{ secrets.SUPER_ADMIN_DOMAIN }}
            TENANT_DOMAIN_PREFIX=immigration-portal
            API_BASE_URL=${{ secrets.API_BASE_URL }}
            EC2_PUBLIC_IP=${{ secrets.EC2_PUBLIC_IP }}
            EC2_PRIVATE_IP=${{ secrets.EC2_PRIVATE_IP }}
            EC2_PUBLIC_DNS=${{ secrets.EC2_PUBLIC_DNS }}
            TENANT_API_BASE_URL=https://{domain}/immigration-portal
            TENANT_API_VERSION=v1
            CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}
            CLOUDFLARE_ZONE_ID=${{ secrets.CLOUDFLARE_ZONE_ID }}
            CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            MAIN_DOMAIN=${{ secrets.MAIN_DOMAIN }}
            EOF
            
            # Make deploy script executable and run it
            chmod +x deploy.sh
            ./deploy.sh
